name: Coffee Shop CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check code style
      run: ./gradlew ktlintCheck || echo "ktlint not configured, skipping"

    - name: Run static code analysis
      run: ./gradlew detekt || echo "detekt not configured, skipping"

  build:
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Build Fat JAR
      run: ./gradlew buildFatJar

    - name: Upload Fat JAR
      uses: actions/upload-artifact@v4
      with:
        name: coffee-shop-application
        path: coffee-shop-application/build/libs/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Download Fat JAR
      uses: actions/download-artifact@v4
      with:
        name: coffee-shop-application
        path: coffee-shop-application/build/libs/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./coffee-shop-application
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/coffee-shop-application:latest
        file: ./coffee-shop-application/Dockerfile
